// Constants barrel — named re-exports only (no `export *`)

// VM Sizes
export {
  canSatisfyVmSize,
  DEFAULT_VM_SIZE_VCPUS,
  getVcpuCount,
  PROVIDER_VM_SIZE_VCPUS,
  VM_SIZE_LABELS,
  vmSizeFallbackChain,
} from './vm-sizes';

// Providers & Locations
export type { LocationMeta, ProviderHelpMeta } from './providers';
export {
  getDefaultLocationForProvider,
  getLocationsForProvider,
  isValidLocationForProvider,
  isValidProvider,
  PROVIDER_DEFAULT_LOCATIONS,
  PROVIDER_HELP,
  PROVIDER_LABELS,
  PROVIDER_LOCATIONS,
  VM_LOCATIONS,
} from './providers';

// Status
export { STATUS_COLORS, STATUS_LABELS } from './status';

// Defaults & Limits
export {
  DEFAULT_BRANCH,
  DEFAULT_CHAT_COMPACT_MODE,
  DEFAULT_CHAT_SESSION_MESSAGE_LIMIT,
  DEFAULT_DASHBOARD_INACTIVE_THRESHOLD_MS,
  DEFAULT_DASHBOARD_POLL_INTERVAL_MS,
  DEFAULT_MAX_AGENT_SESSIONS_PER_WORKSPACE,
  DEFAULT_MAX_NODES_PER_USER,
  DEFAULT_MAX_PROJECT_RUNTIME_ENV_VALUE_BYTES,
  DEFAULT_MAX_PROJECT_RUNTIME_ENV_VARS_PER_PROJECT,
  DEFAULT_MAX_PROJECT_RUNTIME_FILE_CONTENT_BYTES,
  DEFAULT_MAX_PROJECT_RUNTIME_FILE_PATH_LENGTH,
  DEFAULT_MAX_PROJECT_RUNTIME_FILES_PER_PROJECT,
  DEFAULT_MAX_PROJECTS_PER_USER,
  DEFAULT_MAX_TASK_DEPENDENCIES_PER_TASK,
  DEFAULT_MAX_TASKS_PER_PROJECT,
  DEFAULT_MCP_TOKEN_MAX_LIFETIME_SECONDS,
  DEFAULT_MCP_TOKEN_TTL_SECONDS,
  DEFAULT_NODE_HEARTBEAT_STALE_SECONDS,
  DEFAULT_TASK_CALLBACK_RETRY_MAX_ATTEMPTS,
  DEFAULT_TASK_CALLBACK_TIMEOUT_MS,
  DEFAULT_TASK_LIST_DEFAULT_PAGE_SIZE,
  DEFAULT_TASK_LIST_MAX_PAGE_SIZE,
  DEFAULT_VM_LOCATION,
  DEFAULT_VM_SIZE,
  DEFAULT_WORKSPACE_PROFILE,
  DEVCONTAINER_CONFIG_NAME_MAX_LENGTH,
  DEVCONTAINER_CONFIG_NAME_REGEX,
  VALID_WORKSPACE_PROFILES,
  WORKSPACE_NAME_MAX_LENGTH,
} from './defaults';

// Task Execution
export {
  DEFAULT_MAX_WORKSPACES_PER_NODE,
  DEFAULT_TASK_RUN_CLEANUP_DELAY_MS,
  DEFAULT_TASK_RUN_HARD_TIMEOUT_MS,
  DEFAULT_TASK_RUN_MAX_EXECUTION_MS,
  DEFAULT_TASK_RUN_NODE_CPU_THRESHOLD_PERCENT,
  DEFAULT_TASK_RUN_NODE_MEMORY_THRESHOLD_PERCENT,
  DEFAULT_TASK_RUNNER_AGENT_POLL_INTERVAL_MS,
  DEFAULT_TASK_RUNNER_AGENT_READY_TIMEOUT_MS,
  DEFAULT_TASK_RUNNER_PROVISION_POLL_INTERVAL_MS,
  DEFAULT_TASK_RUNNER_PROVISION_TIMEOUT_MS,
  DEFAULT_TASK_RUNNER_RETRY_BASE_DELAY_MS,
  DEFAULT_TASK_RUNNER_RETRY_MAX_DELAY_MS,
  DEFAULT_TASK_RUNNER_STEP_MAX_RETRIES,
  DEFAULT_TASK_RUNNER_WORKSPACE_DISPATCH_BASE_DELAY_MS,
  DEFAULT_TASK_RUNNER_WORKSPACE_DISPATCH_MAX_DELAY_MS,
  DEFAULT_TASK_RUNNER_WORKSPACE_DISPATCH_TIMEOUT_MS,
  DEFAULT_TASK_RUNNER_WORKSPACE_READY_POLL_INTERVAL_MS,
  DEFAULT_TASK_RUNNER_WORKSPACE_READY_TIMEOUT_MS,
  DEFAULT_TASK_STUCK_DELEGATED_TIMEOUT_MS,
  DEFAULT_TASK_STUCK_QUEUED_TIMEOUT_MS,
} from './task-execution';

// Node Pooling & Idle Timeout
export {
  DEFAULT_MAX_AUTO_NODE_LIFETIME_MS,
  DEFAULT_NODE_LIFECYCLE_ALARM_RETRY_MS,
  DEFAULT_NODE_WARM_GRACE_PERIOD_MS,
  DEFAULT_NODE_WARM_TIMEOUT_MS,
  DEFAULT_ORPHANED_WORKSPACE_GRACE_PERIOD_MS,
  DEFAULT_WORKSPACE_IDLE_TIMEOUT_MS,
  DEFAULT_WORKSPACE_STOPPED_TTL_MS,
  MAX_NODE_IDLE_TIMEOUT_MS,
  MAX_WORKSPACE_IDLE_TIMEOUT_MS,
  MIN_NODE_IDLE_TIMEOUT_MS,
  MIN_WORKSPACE_IDLE_TIMEOUT_MS,
  TERMINAL_ACTIVITY_THROTTLE_MS,
  WORKSPACE_IDLE_CHECK_INTERVAL_MS,
} from './node-pooling';

// Scaling Parameters
export type { ScalingParamKey, ScalingParamMeta } from './scaling';
export {
  DEFAULT_MAX_CONCURRENT_TASKS,
  DEFAULT_MAX_DISPATCH_DEPTH,
  DEFAULT_MAX_SUB_TASKS_PER_TASK,
  DEFAULT_NODE_CPU_THRESHOLD_PERCENT,
  DEFAULT_NODE_MEMORY_THRESHOLD_PERCENT,
  DEFAULT_TASK_EXECUTION_TIMEOUT_MS,
  MAX_MAX_CONCURRENT_TASKS,
  MAX_MAX_DISPATCH_DEPTH,
  MAX_MAX_SUB_TASKS_PER_TASK,
  MAX_MAX_WORKSPACES_PER_NODE,
  MAX_NODE_CPU_THRESHOLD_PERCENT,
  MAX_NODE_MEMORY_THRESHOLD_PERCENT,
  MAX_TASK_EXECUTION_TIMEOUT_MS,
  MAX_WARM_NODE_TIMEOUT_MS,
  MIN_MAX_CONCURRENT_TASKS,
  MIN_MAX_DISPATCH_DEPTH,
  MIN_MAX_SUB_TASKS_PER_TASK,
  MIN_MAX_WORKSPACES_PER_NODE,
  MIN_NODE_CPU_THRESHOLD_PERCENT,
  MIN_NODE_MEMORY_THRESHOLD_PERCENT,
  MIN_TASK_EXECUTION_TIMEOUT_MS,
  MIN_WARM_NODE_TIMEOUT_MS,
  resolveProjectScalingConfig,
  SCALING_PARAMS,
} from './scaling';

// Hetzner / Scaleway / GCP Provider Defaults
export {
  DEFAULT_GCP_API_TIMEOUT_MS,
  DEFAULT_GCP_DISK_SIZE_GB,
  DEFAULT_GCP_IDENTITY_TOKEN_EXPIRY_SECONDS,
  DEFAULT_GCP_IMAGE_FAMILY,
  DEFAULT_GCP_IMAGE_PROJECT,
  DEFAULT_GCP_OPERATION_POLL_TIMEOUT_MS,
  DEFAULT_GCP_SA_IMPERSONATION_SCOPES,
  DEFAULT_GCP_SA_TOKEN_LIFETIME_SECONDS,
  DEFAULT_GCP_SERVICE_ACCOUNT_ID,
  DEFAULT_GCP_STS_SCOPE,
  DEFAULT_GCP_TOKEN_CACHE_TTL_SECONDS,
  DEFAULT_GCP_WIF_POOL_ID,
  DEFAULT_GCP_WIF_PROVIDER_ID,
  DEFAULT_GCP_ZONE,
  DEFAULT_HETZNER_DATACENTER,
  DEFAULT_HETZNER_IMAGE,
  DEFAULT_SCALEWAY_IMAGE_NAME,
  DEFAULT_SCALEWAY_ZONE,
  HETZNER_IMAGE,
} from './hetzner';

// GCP Deployment
export {
  DEFAULT_GCP_DEPLOY_IDENTITY_TOKEN_EXPIRY_SECONDS,
  DEFAULT_GCP_DEPLOY_OAUTH_STATE_TTL_SECONDS,
  DEFAULT_GCP_DEPLOY_OAUTH_TOKEN_HANDLE_TTL_SECONDS,
  DEFAULT_GCP_DEPLOY_SERVICE_ACCOUNT_ID,
  DEFAULT_GCP_DEPLOY_WIF_POOL_ID,
  DEFAULT_GCP_DEPLOY_WIF_PROVIDER_ID,
  DEFAULT_GCP_IAM_CREDENTIALS_BASE_URL,
  DEFAULT_GCP_STS_TOKEN_URL,
} from './gcp-deployment';

// AI Services (Task Title, Context Summary, TTS, AI Proxy)
export {
  AGENT_LOOP_MIN_TOOL_CALL_SUPPORT,
  AI_ADMIN_ALLOWANCE_KV_PREFIX,
  AI_BUDGET_SETTINGS_KV_PREFIX,
  AI_MONTHLY_COST_CACHE_KV_PREFIX,
  AI_PROXY_BILLING_MODE_KV_KEY,
  AI_PROXY_DEFAULT_MODEL_KV_KEY,
  type AIProxyConfig,
  type BillingMode,
  DEFAULT_AI_MONTHLY_COST_CACHE_TTL_SECONDS,
  DEFAULT_AI_PROXY_ALLOWED_MODELS,
  DEFAULT_AI_PROXY_ANTHROPIC_MODEL,
  DEFAULT_AI_PROXY_BILLING_MODE,
  DEFAULT_AI_PROXY_DAILY_INPUT_TOKEN_LIMIT,
  DEFAULT_AI_PROXY_DAILY_OUTPUT_TOKEN_LIMIT,
  DEFAULT_AI_PROXY_MAX_INPUT_TOKENS_PER_REQUEST,
  DEFAULT_AI_PROXY_MODEL,
  DEFAULT_AI_PROXY_OPENAI_MODEL,
  DEFAULT_AI_PROXY_RATE_LIMIT_RPM,
  DEFAULT_AI_PROXY_RATE_LIMIT_WINDOW_SECONDS,
  DEFAULT_AI_PROXY_STREAM_TIMEOUT_MS,
  DEFAULT_AI_USAGE_ALERT_THRESHOLD_PERCENT,
  DEFAULT_AI_USAGE_BUDGET_TTL_SECONDS,
  DEFAULT_AI_USAGE_MAX_DAILY_TOKEN_LIMIT,
  DEFAULT_AI_USAGE_MAX_MONTHLY_COST_CAP_USD,
  DEFAULT_AI_USAGE_MIN_DAILY_TOKEN_LIMIT,
  DEFAULT_AI_USAGE_MIN_MONTHLY_COST_CAP_USD,
  DEFAULT_CONTEXT_SUMMARY_HEAD_MESSAGES,
  DEFAULT_CONTEXT_SUMMARY_HEURISTIC_RECENT_MESSAGES,
  DEFAULT_CONTEXT_SUMMARY_MAX_LENGTH,
  DEFAULT_CONTEXT_SUMMARY_MAX_MESSAGES,
  DEFAULT_CONTEXT_SUMMARY_MODEL,
  DEFAULT_CONTEXT_SUMMARY_RECENT_MESSAGES,
  DEFAULT_CONTEXT_SUMMARY_SHORT_THRESHOLD,
  DEFAULT_CONTEXT_SUMMARY_TIMEOUT_MS,
  DEFAULT_SANDBOX_AGENT_MAX_TURNS,
  DEFAULT_SANDBOX_MODEL,
  DEFAULT_TASK_TITLE_MAX_LENGTH,
  DEFAULT_TASK_TITLE_MAX_RETRIES,
  DEFAULT_TASK_TITLE_MODEL,
  DEFAULT_TASK_TITLE_RETRY_DELAY_MS,
  DEFAULT_TASK_TITLE_RETRY_MAX_DELAY_MS,
  DEFAULT_TASK_TITLE_SHORT_MESSAGE_THRESHOLD,
  DEFAULT_TASK_TITLE_TIMEOUT_MS,
  DEFAULT_TTS_CHUNK_SIZE,
  DEFAULT_TTS_CLEANUP_MAX_TOKENS,
  DEFAULT_TTS_CLEANUP_MODEL,
  DEFAULT_TTS_CLEANUP_TIMEOUT_MS,
  DEFAULT_TTS_ENCODING,
  DEFAULT_TTS_MAX_CHUNKS,
  DEFAULT_TTS_MAX_TEXT_LENGTH,
  DEFAULT_TTS_MODEL,
  DEFAULT_TTS_R2_PREFIX,
  DEFAULT_TTS_RETRY_ATTEMPTS,
  DEFAULT_TTS_RETRY_BASE_DELAY_MS,
  DEFAULT_TTS_SPEAKER,
  DEFAULT_TTS_SUMMARY_THRESHOLD,
  DEFAULT_TTS_TIMEOUT_MS,
  filterModelsForAgentLoop,
  MAX_CONTEXT_SUMMARY_BYTES,
  type ModelAllowedScope,
  type ModelIntendedRole,
  PLATFORM_AI_MODELS,
  type PlatformAIModel,
  type PlatformAIModelTier,
  type ToolCallSupport,
  VALID_BILLING_MODES,
} from './ai-services';

// Agent Settings
export {
  AGENT_PERMISSION_MODE_DESCRIPTIONS,
  AGENT_PERMISSION_MODE_LABELS,
  VALID_PERMISSION_MODES,
} from './agent-settings';

// Triggers (Event-Driven Agent Triggers)
export {
  DEFAULT_CRON_MAX_FIRE_PER_SWEEP,
  DEFAULT_CRON_MIN_INTERVAL_MINUTES,
  DEFAULT_CRON_TEMPLATE_MAX_FIELD_LENGTH,
  DEFAULT_CRON_TEMPLATE_MAX_LENGTH,
  DEFAULT_MAX_TRIGGERS_PER_PROJECT,
  DEFAULT_TRIGGER_AUTO_PAUSE_AFTER_FAILURES,
  DEFAULT_TRIGGER_DEFAULT_MAX_CONCURRENT,
  DEFAULT_TRIGGER_DESCRIPTION_MAX_LENGTH,
  DEFAULT_TRIGGER_EXECUTION_LOG_RETENTION_DAYS,
  DEFAULT_TRIGGER_MAX_CONCURRENT_LIMIT,
  DEFAULT_TRIGGER_NAME_MAX_LENGTH,
  DEFAULT_TRIGGER_STALE_EXECUTION_TIMEOUT_MS,
  DEFAULT_TRIGGER_STALE_QUEUED_TIMEOUT_MS,
  TRIGGER_DEFAULTS,
} from './triggers';

// Trial Orchestrator (alarm-driven trial provisioning DO)
export {
  DEFAULT_TRIAL_KNOWLEDGE_GITHUB_TIMEOUT_MS,
  DEFAULT_TRIAL_KNOWLEDGE_MAX_EVENTS,
  DEFAULT_TRIAL_ORCHESTRATOR_AGENT_READY_TIMEOUT_MS,
  DEFAULT_TRIAL_ORCHESTRATOR_HEARTBEAT_SKEW_MS,
  DEFAULT_TRIAL_ORCHESTRATOR_NODE_READY_TIMEOUT_MS,
  DEFAULT_TRIAL_ORCHESTRATOR_OVERALL_TIMEOUT_MS,
  DEFAULT_TRIAL_ORCHESTRATOR_RETRY_BASE_DELAY_MS,
  DEFAULT_TRIAL_ORCHESTRATOR_RETRY_MAX_DELAY_MS,
  DEFAULT_TRIAL_ORCHESTRATOR_STEP_MAX_RETRIES,
  DEFAULT_TRIAL_ORCHESTRATOR_WORKSPACE_READY_POLL_INTERVAL_MS,
  DEFAULT_TRIAL_ORCHESTRATOR_WORKSPACE_READY_TIMEOUT_MS,
} from './trial-orchestrator';

// Missions (Phase 2: Orchestration Primitives)
export type { HandoffLimits, MissionStateLimits } from './missions';
export {
  DEFAULT_HANDOFF_MAX_ARTIFACT_REFS,
  DEFAULT_HANDOFF_MAX_FACTS,
  DEFAULT_HANDOFF_MAX_OPEN_QUESTIONS,
  DEFAULT_HANDOFF_MAX_SUGGESTED_ACTIONS,
  DEFAULT_HANDOFF_SUMMARY_MAX_LENGTH,
  DEFAULT_MISSION_DESCRIPTION_MAX_LENGTH,
  DEFAULT_MISSION_LIST_MAX_PAGE_SIZE,
  DEFAULT_MISSION_LIST_PAGE_SIZE,
  DEFAULT_MISSION_MAX_HANDOFFS,
  DEFAULT_MISSION_MAX_PER_PROJECT,
  DEFAULT_MISSION_MAX_STATE_ENTRIES,
  DEFAULT_MISSION_STATE_CONTENT_MAX_LENGTH,
  DEFAULT_MISSION_STATE_TITLE_MAX_LENGTH,
  DEFAULT_MISSION_TITLE_MAX_LENGTH,
  resolveHandoffLimits,
  resolveMissionStateLimits,
} from './missions';

// Orchestrator (Phase 3: Project Orchestrator)
export type { OrchestratorConfig } from './orchestrator';
export {
  DEFAULT_ORCHESTRATOR_DECISION_LOG_MAX_ENTRIES,
  DEFAULT_ORCHESTRATOR_MAX_ACTIVE_TASKS_PER_MISSION,
  DEFAULT_ORCHESTRATOR_MAX_DISPATCHES_PER_CYCLE,
  DEFAULT_ORCHESTRATOR_QUEUE_MAX_ENTRIES,
  DEFAULT_ORCHESTRATOR_RECENT_DECISIONS_LIMIT,
  DEFAULT_ORCHESTRATOR_SCHEDULING_INTERVAL_MS,
  DEFAULT_ORCHESTRATOR_STALL_TIMEOUT_MS,
  resolveOrchestratorConfig,
} from './orchestrator';

// Task Reconciliation (Inactivity Check-In)
export {
  DEFAULT_TASK_RECONCILIATION_IDLE_MS,
  DEFAULT_TASK_RECONCILIATION_RESPONSE_DEADLINE_MS,
} from './reconciliation';

// Policies (Phase 4: Policy Propagation)
export type { PolicyLimits } from './policies';
export {
  DEFAULT_POLICY_CONFIDENCE,
  DEFAULT_POLICY_CONTENT_MAX_LENGTH,
  DEFAULT_POLICY_LIST_MAX_PAGE_SIZE,
  DEFAULT_POLICY_LIST_PAGE_SIZE,
  DEFAULT_POLICY_MAX_PER_PROJECT,
  DEFAULT_POLICY_TITLE_MAX_LENGTH,
  resolvePolicyLimits,
} from './policies';

// Notifications
export type { HumanInputCategory } from './notifications';
export {
  DEFAULT_MAX_NOTIFICATIONS_PER_USER,
  DEFAULT_NOTIFICATION_AUTO_DELETE_AGE_MS,
  DEFAULT_NOTIFICATION_DEDUP_WINDOW_MS,
  DEFAULT_NOTIFICATION_FULL_BODY_LENGTH,
  DEFAULT_NOTIFICATION_PAGE_SIZE,
  DEFAULT_NOTIFICATION_PROGRESS_BATCH_WINDOW_MS,
  HUMAN_INPUT_CATEGORIES,
  MAX_HUMAN_INPUT_CONTEXT_LENGTH,
  MAX_HUMAN_INPUT_OPTION_LENGTH,
  MAX_HUMAN_INPUT_OPTIONS_COUNT,
  MAX_NOTIFICATION_BODY_LENGTH,
  MAX_NOTIFICATION_PAGE_SIZE,
  MAX_NOTIFICATION_TITLE_LENGTH,
  MAX_NOTIFICATION_TITLE_LENGTH_NEEDS_INPUT,
  NOTIFICATION_PREVIEW_LENGTH,
  NOTIFICATION_TYPE_URGENCY,
} from './notifications';

// SAM Agent (Top-Level Agent)
export type { SamConfig } from './sam';
export {
  DEFAULT_SAM_AIG_SOURCE,
  DEFAULT_SAM_CONVERSATION_CONTEXT_WINDOW,
  DEFAULT_SAM_FTS_ENABLED,
  DEFAULT_SAM_HISTORY_LOAD_LIMIT,
  DEFAULT_SAM_MAX_CONVERSATIONS,
  DEFAULT_SAM_MAX_MESSAGES_PER_CONVERSATION,
  DEFAULT_SAM_MAX_REQUEST_BODY_BYTES,
  DEFAULT_SAM_MAX_REQUEST_BODY_BYTES_WORKERS_AI,
  DEFAULT_SAM_MAX_TOKENS,
  DEFAULT_SAM_MAX_TOOL_RESULT_BYTES,
  DEFAULT_SAM_MAX_TURNS,
  DEFAULT_SAM_MODEL,
  DEFAULT_SAM_RATE_LIMIT_RPM,
  DEFAULT_SAM_RATE_LIMIT_WINDOW_SECONDS,
  DEFAULT_SAM_SEARCH_LIMIT,
  DEFAULT_SAM_SEARCH_MAX_LIMIT,
  resolveSamConfig,
  SAM_ANTHROPIC_VERSION,
} from './sam';

// Resource Defaults & Resolver
export type { VmCapacity } from './resource-defaults';
export {
  DEFAULT_VM_CAPACITY,
  PLATFORM_RESOURCE_DEFAULTS,
  PROVIDER_VM_CAPACITY,
  resolveResourceReservation,
  RESOURCE_RESERVATION_VERSION,
  selectVmSizeForRequirements,
} from './resource-defaults';
