import { describe, expect, it, test } from 'vitest';

import type { Provider } from '../../src/types';
import { expectDefined } from '../unit/test-helpers';

// Marker test so vitest accepts this file (actual tests are generated by runProviderContractTests)
test('provider contract suite is importable', () => {
  expect(typeof runProviderContractTests).toBe('function');
});

/**
 * Reusable contract test suite for Provider implementations.
 * Any provider can call this function with its own factory to verify interface compliance.
 *
 * The factory should return a fully configured provider instance.
 * The provider's external API calls should be mocked before calling this function.
 */
export function runProviderContractTests(
  createProvider: () => Provider,
  options?: {
    /** Description prefix for the test suite */
    name?: string;
    /** Whether createVM is expected to return an IP immediately. */
    createReturnsIp?: boolean;
  },
) {
  const suiteName = options?.name || 'Provider Contract';
  const createReturnsIp = options?.createReturnsIp ?? true;

  describe(suiteName, () => {
    let provider: Provider;

    // Create a fresh provider for each test
    const getProvider = () => {
      provider = createProvider();
      return provider;
    };

    describe('readonly properties', () => {
      it('should have a non-empty name', () => {
        const p = getProvider();
        expect(p.name).toBeTruthy();
        expect(typeof p.name).toBe('string');
      });

      it('should have a non-empty locations array', () => {
        const p = getProvider();
        expect(Array.isArray(p.locations)).toBe(true);
        expect(p.locations.length).toBeGreaterThan(0);
        for (const loc of p.locations) {
          expect(typeof loc).toBe('string');
        }
      });

      it('should have sizes for small, medium, and large', () => {
        const p = getProvider();
        for (const size of ['small', 'medium', 'large'] as const) {
          const config = p.sizes[size];
          expect(config).toBeDefined();
          expect(config.type).toBeTruthy();
          expect(config.price).toBeTruthy();
          expect(config.vcpu).toBeGreaterThan(0);
          expect(config.ramGb).toBeGreaterThan(0);
          expect(config.storageGb).toBeGreaterThan(0);
        }
      });

      it('should have increasing resources from small to large', () => {
        const p = getProvider();
        expect(p.sizes.medium.vcpu).toBeGreaterThanOrEqual(p.sizes.small.vcpu);
        expect(p.sizes.large.vcpu).toBeGreaterThanOrEqual(p.sizes.medium.vcpu);
        expect(p.sizes.medium.ramGb).toBeGreaterThanOrEqual(p.sizes.small.ramGb);
        expect(p.sizes.large.ramGb).toBeGreaterThanOrEqual(p.sizes.medium.ramGb);
      });
    });

    describe('createVM', () => {
      it('should return a VMInstance with all required fields', async () => {
        const p = getProvider();
        const result = await p.createVM({
          name: 'contract-test',
          size: 'small',
          location: expectDefined(p.locations[0]),
          userData: '#cloud-config\n',
        });

        expect(result.id).toBeTruthy();
        expect(typeof result.id).toBe('string');
        expect(result.name).toBeTruthy();
        if (createReturnsIp) {
          expect(result.ip).toBeTruthy();
        } else {
          expect(typeof result.ip).toBe('string');
        }
        expect(result.status).toBeTruthy();
        expect(result.serverType).toBeTruthy();
        expect(result.createdAt).toBeTruthy();
        expect(typeof result.labels).toBe('object');
      });
    });

    describe('deleteVM', () => {
      it('should be idempotent (no error on 404)', async () => {
        const p = getProvider();
        // Deleting a non-existent VM should not throw
        await expect(p.deleteVM('non-existent-id')).resolves.not.toThrow();
      });
    });

    describe('getVM', () => {
      it('should return null for non-existent VM', async () => {
        const p = getProvider();
        const result = await p.getVM('non-existent-id');
        expect(result).toBeNull();
      });
    });

    describe('listVMs', () => {
      it('should return an array', async () => {
        const p = getProvider();
        const result = await p.listVMs();
        expect(Array.isArray(result)).toBe(true);
      });

      it('should return an array when called with label filters', async () => {
        const p = getProvider();
        const result = await p.listVMs({ 'managed-by': 'test' });
        expect(Array.isArray(result)).toBe(true);
      });
    });

    describe('powerOff', () => {
      it('should not throw on valid call', async () => {
        const p = getProvider();
        await expect(p.powerOff('test-id')).resolves.not.toThrow();
      });
    });

    describe('powerOn', () => {
      it('should not throw on valid call', async () => {
        const p = getProvider();
        await expect(p.powerOn('test-id')).resolves.not.toThrow();
      });
    });

    describe('validateToken', () => {
      it('should return a boolean', async () => {
        const p = getProvider();
        const result = await p.validateToken();
        expect(typeof result).toBe('boolean');
      });
    });
  });
}
